---
name: "Release collection ðŸš€"
on: # yamllint disable-line rule:truthy
  release:
    types: [published]
jobs:
  release_automation_hub:
    uses: ansible/ansible-content-actions/.github/workflows/release_ah.yaml@main
    with:
      environment: release
      ah_publish: false
  release_galaxy:
    uses: ansible/ansible-content-actions/.github/workflows/release_galaxy.yaml@main
    needs:
      - release_automation_hub
    with:
      environment: release
    secrets:
      ansible_galaxy_api_key: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
